---
# tasks file for web
- name: setup opencfp
  user: name=opencfp

- name: install git
  apt: name=git

- name: create dir for app
  file: path=/var/www/html/opencfp state=directory owner=opencfp

- name: checkout the app code
  git: repo=https://github.com/zhenqing/opencfp.git dest=/var/www/html/opencfp
  become_user: opencfp

- name: upload phinx.yml
  copy: src=/home/vagrant/src/opencfp/phinx.yml dest=/var/www/html/opencfp/phinx.yml owner=opencfp group=opencfp mode=0644

- name: upload production.yml
  copy: src=/home/vagrant/src/opencfp/config/production.yml dest=/var/www/html/opencfp/config/production.yml owner=opencfp group=opencfp mode=0644

- name: db migration
  command: php vendor/bin/phinx migrate -e production chdir=/var/www/html/opencfp
  become_user: opencfp
